version: '3.7'
services:
  backend:
    container_name:
      simple-api
    build:
      ./simple-api/
    networks:
      - my-app-network
    depends_on:
      - database
  frontend:
    container_name: 
      devops-front
    build:
      ./devops-front/
    networks:
      - my-app-network
    depends_on:
      - database
      - backend
  database:
    container_name: 
      postgres
    build:
      ./psql
    networks:
      - my-app-network  
    volumes:
      - ~/psqldata/:/var/lib/postgresql/data
  httpd:
    container_name: 
      my-apache-server
    build:
      ./apache
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - my-app-network
    depends_on:
      - backend
      - database
      - frontend
networks:
  my-app-network: