---
# tasks file for roles/proxy
- name: Run proxy container
  docker_container:
    name: my-apache-server
    image: eloibrd/my-apache-server
    ports:
      - "80:80" # on expose le front
      - "8080:8080" # on expose l'api
    networks:
      - name: app-network
    pull: true